services:
  - type: web
    name: progressivbauconcept
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
